### 客户端下载链接 API 测试

### 环境变量
@host = http://localhost:6400
@testUrl = https://www.kdocs.cn/l/ck0azivLlDi3
@testPwd = 
@cowUrl = https://cowtransfer.com/s/test123

@lanzouUrl = https://wwsd.lanzoue.com/iLany1e9bbbi

### 1. 获取所有客户端下载链接
GET {{host}}/v2/clientLinks?url={{lanzouUrl}}&pwd={{testPwd}}

### 2. 获取指定类型的客户端下载链接 - cURL
GET {{host}}/v2/clientLink?url={{testUrl}}&pwd={{testPwd}}&clientType=curl

### 3. 获取指定类型的客户端下载链接 - PowerShell
GET {{host}}/v2/clientLink?url={{testUrl}}&pwd={{testPwd}}&clientType=powershell

### 4. 获取指定类型的客户端下载链接 - Aria2
GET {{host}}/v2/clientLink?url={{testUrl}}&pwd={{testPwd}}&clientType=aria2

### 5. 获取指定类型的客户端下载链接 - 迅雷
GET {{host}}/v2/clientLink?url={{testUrl}}&pwd={{testPwd}}&clientType=thunder

### 6. 获取指定类型的客户端下载链接 - IDM
GET {{host}}/v2/clientLink?url={{testUrl}}&pwd={{testPwd}}&clientType=idm

### 7. 获取指定类型的客户端下载链接 - wget
GET {{host}}/v2/clientLink?url={{testUrl}}&pwd={{testPwd}}&clientType=wget

### 8. 获取指定类型的客户端下载链接 - 比特彗星
GET {{host}}/v2/clientLink?url={{testUrl}}&pwd={{testPwd}}&clientType=bitcomet

### 9. 获取指定类型的客户端下载链接 - Motrix
GET {{host}}/v2/clientLink?url={{testUrl}}&pwd={{testPwd}}&clientType=motrix

### 10. 获取指定类型的客户端下载链接 - FDM
GET {{host}}/v2/clientLink?url={{testUrl}}&pwd={{testPwd}}&clientType=fdm

### 11. 测试不支持的客户端类型
GET {{host}}/v2/clientLink?url={{testUrl}}&pwd={{testPwd}}&clientType=invalid

### 12. 测试奶牛快传（需要 Referer）
GET {{host}}/v2/clientLinks?url={{cowUrl}}&pwd=

### 13. 测试空参数
GET {{host}}/v2/clientLinks

### 14. 测试无效URL
GET {{host}}/v2/clientLinks?url=invalid-url&pwd=1234