POST https://www.wenshushu.cn/ap/ufile/nlist
Accept: application/json, text/plain, */*
X-Token: 2QujUq7M4xZpkeydcAnOmk4FVqw

{"start":0,"sort":{"name":"asc"},"bid":"5zl01fgbops","pid":"5zl01fgehuo","options":{"uploader":"true"},"size":50}

###
# @no-cookie-jar
POST https://www.wenshushu.cn/ap/user/userinfo
Accept: application/json, text/plain, */*
X-Token: 2QujUq7M4xZpkeydcAnOmk4FVqw

{"plat":"pcweb"}



### 分享文件信息 (有效期)
# https://t.wss.ink/f/bekolxi7hqb
POST https://www.wenshushu.cn/ap/task/mgrtask
Accept: application/json, text/plain, */*
X-Token: 2QujUq7M4xZpkeydcAnOmk4FVqw

{"tid":"bekolxi7hqb","password":""}

### 分享延期 需要<24小时 延期间隔=?
POST https://www.wenshushu.cn/ap/task/delay
Accept: application/json, text/plain, */*
X-Token: 2QujUq7M4xZpkeydcAnOmk4FVqw

{"tid":"bekolxi7hqb","delay_time":1,"is_extension":false}


### 获取匿名TOKEN
POST https://www.wenshushu.cn/ap/login/anonymous
Accept: application/json, text/plain, */*

### 获取下载文件URL
POST https://www.wenshushu.cn/ap/dl/sign
Accept: application/json, text/plain, */*
X-Token:wss:br57uq0qg03

{"ufileid":"br4t1rst6xb","consumeCode":0,"type":1}

###
# {
#  "code": 0,
#  "message": "success",
#  "data": {
#    "url": "https://down.wss.show/zkrk4th/9/yj/9yjvzkrk4th?cdn_sign=1686211254-31-0-6edd2e228a030be23210158daeb2c4a1&exp=4800&response-content-disposition=attachment%3B%20filename%3D%22supervision.sql%22%3B%20filename%2A%3Dutf-8%27%27supervision.sql",

### 直接下载
https://down.wss.show/zkrk4th/9/yj/9yjvzkrk4th?cdn_sign=1690012643-63-0-f7761ba9a500a0b300a3b5573693f9ce&exp=4800&response-content-disposition=attachment%3B%20filename%3D%22supervision.sql%22%3B%20filename%2A%3Dutf-8%27%27supervision.sql

### https://115.com/s/sw6tqra3zti?password=vc30#boost.files
https://webapi.115.com/share/downurl?user_id=101200613&share_code=sw6tqra3zti&file_id=2643992364552551890&receive_code=vc30
Cookie: UID=101200613_A1_1690425668; CID=29ac00cab116eeda63fce2296179b5ad; SEID=8f0385cd8a10f4bb8db7b064ff55ae8f53f8c7e7c6f61a3f6b1eee234d31f08bf00ac9dc68c6ff38005788e0b8444751a6b35a3f9654b07d3e4d7a67

###
https://cdnfhnfile.115.com/64722de2d26c69c339bd4c1322a0a7714717d15f/boost.files?t=1690427063&u=101200613&s=1048576&d=1894289998--0&c=0&f=3&k=53d82265b751466ee0581d1638327605&us=52428800&uc=10&v=1

###
https://webapi.115.com/share/snap?share_code=sw6tqra3zti&offset=0&limit=20&receive_code=vc30
