### 亿方云分享 重定向
# @no-redirect
https://v2.fangcloud.com/sharing/9cbe4b73521ba4d65a8cd38a8c

### get重定向 set-cookie: fc_session
https://share-d94258c2ebfde2a83a7d5931e8da5221.fangcloud.cn/share/9cbe4b73521ba4d65a8cd38a8c

### cookie: fc_session=xxx 获取file_id
# @no-cookie-jar
https://share-d94258c2ebfde2a83a7d5931e8da5221.fangcloud.cn/apps/files/get_info?scenario=share&item_typed_id=file_559003251828
Cookie:fc_session=eyJpdiI6IndQYzJoVkdQWjhJSmNOYVIwZnpiTVE9PSIsInZhbHVlIjoiUThocXBGcHA3MXN0SHZYV3R1a282djlpWEl0YmlxMzE2SUpFUjZQbFwvMytoU0NjNXRVbm10ejg0b1wvaVpSZXJaUVRIeTV2NmlvUDZlMlJsRnEyRTY1Zz09IiwibWFjIjoiNGM2NTFkN2Q2NTI3ZWUwOTc2ZmY1ODUzODEzYWRkZjIyNjg0ZGM1NDhhZDg1NjU1NzRkNjZiZWFjOGYyOWYxZiJ9

#{
#   "success": true
#  "item": {
#    "extension": "apk",
#    "id": 559003251828, // file_id

### 获取下载链接
# @no-redirect
# @no-cookie-jar
https://share-d94258c2ebfde2a83a7d5931e8da5221.fangcloud.cn/apps/files/download?file_id=559003251828&scenario=share&unique_name=9cbe4b73521ba4d65a8cd38a8c
Cookie:fc_session=eyJpdiI6IndQYzJoVkdQWjhJSmNOYVIwZnpiTVE9PSIsInZhbHVlIjoiUThocXBGcHA3MXN0SHZYV3R1a282djlpWEl0YmlxMzE2SUpFUjZQbFwvMytoU0NjNXRVbm10ejg0b1wvaVpSZXJaUVRIeTV2NmlvUDZlMlJsRnEyRTY1Zz09IiwibWFjIjoiNGM2NTFkN2Q2NTI3ZWUwOTc2ZmY1ODUzODEzYWRkZjIyNjg0ZGM1NDhhZDg1NjU1NzRkNjZiZWFjOGYyOWYxZiJ9



### 加密分享
# @no-redirect
https://v2.fangcloud.cn/share/e5079007dc31226096628870c7

### 加密分享
# @no-redirect
# @no-cookie-jar
POST https://v2.fangcloud.cn/share/e5079007dc31226096628870c7
Content-Type: application/x-www-form-urlencoded
Cookie:XSRF-TOKEN=eyJpdiI6IkQ2TlNTOEtBRHZkUWZsVFErcVNPTkE9PSIsInZhbHVlIjoiZXJYUlZVcU94WjlMaThQcU5lU1dHRGJ4TkljVFJYOVpaS0xRS3JldHlBdlwvc3RSakphR1dZK015VkxzbWlBZU5yZFdmaW1yVnk0bWJ6dGhsWEk2b0F3PT0iLCJtYWMiOiIxODI1OGY5NDkwYmY3ZmJhZjMzNDliNTNiNjgxZTM2MTQ2ODhiMGIyNjU3MjQxYzdkNjZkYWMyM2EyMGRjZDg5In0%3D; fc_session=eyJpdiI6IlppZW1UQVwvSHRWSDhVZWZwampkNHZRPT0iLCJ2YWx1ZSI6IjliWlBUZ0VPMlhoTXlUN3hXU25qYjlIdnRQRmtqbFdBR2cyaW1RVDdBN0s5OFRwcGFURjZ3TTZxZnQ4VVRGS2hNbWdPUFhrU0tlUTg1ZTJLZVZFS0FnPT0iLCJtYWMiOiJjMTM0YjI5ZTEwYjQwMGU0MGNlN2UyZmM4MWM2NzAyZmZhYjg5NWNlMjc3ODRhMmIzMzhmODg5ZTZlNzcyMGM2In0%3D; __DC_monitor_count=1; __DC_sid=265210824.1779672371747793700.1686368845992.5159; __guid=265210824.1677826520974775000.1686368845996.6543; device_token=5c99442e32e7b8e5edecd4221f992b41; Hm_lvt_762d2bc251bef4b42a758268dc7edda3=1686367033; Hm_lpvt_762d2bc251bef4b42a758268dc7edda3=1686368846; __DC_gid=265210824.275572345.1686368845996.1686368883043.2
Host:v2.fangcloud.cn
Referer:https://v2.fangcloud.cn/share/e5079007dc31226096628870c7
User-Agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 Edg/114.0.1823.37

requesttoken=se2GpxdjP9zU4rajy1ro3vZ8x0nYE64KdTzgOUtG&password=QAIU

###
# @no-redirect
# @no-cookie-jar
https://v2.fangcloud.cn/share/e5079007dc31226096628870c7
Cookie:XSRF-TOKEN=eyJpdiI6ImVpdW9XOFwvazVka0xRQ2JUQ1p4c1dRPT0iLCJ2YWx1ZSI6Im1NcTJuQW8xdlF4MEg1XC9NZERZUnE4TUgxNm9UYWhoV3pKMlhKcngwakMxR2VHeTFZZ0EzSlBcL244YXlRTWtKZ3NOd1JxYTl4ZktsdXdcL0t5dVlTMXhnPT0iLCJtYWMiOiJhMjZlODE3NDFlMTRkMjg1MzVhMjRjOGVmYTgzYjk1NGM1NmY1N2NmZjljZmIzMmRjZGFmOTVkNDhhMWYwMDRhIn0%3D;  fc_session=eyJpdiI6IlppZW1UQVwvSHRWSDhVZWZwampkNHZRPT0iLCJ2YWx1ZSI6IjliWlBUZ0VPMlhoTXlUN3hXU25qYjlIdnRQRmtqbFdBR2cyaW1RVDdBN0s5OFRwcGFURjZ3TTZxZnQ4VVRGS2hNbWdPUFhrU0tlUTg1ZTJLZVZFS0FnPT0iLCJtYWMiOiJjMTM0YjI5ZTEwYjQwMGU0MGNlN2UyZmM4MWM2NzAyZmZhYjg5NWNlMjc3ODRhMmIzMzhmODg5ZTZlNzcyMGM2In0%3D;

###
# curl 'https://anxia.com/webapi/share/skip_login_downurl'
#  -H 'Accept: application/json, text/javascript, */*; q=0.01'
#  -H 'Accept-Language: zh-CN,zh;q=0.9,en;q=0.8'
#  -H 'Cache-Control: no-cache'
#  -H 'Connection: keep-alive'
#  -H 'Content-Type: application/x-www-form-urlencoded; charset=UTF-8'
#  -H 'Cookie: acw_tc=2f6a1fdb17343237335965711ee089dd42f90058dbad48c86a96931b7098b0'
#  -H 'DNT: 1'
#  -H 'Origin: https://anxia.com'
#  -H 'Pragma: no-cache'
#  -H 'Referer: https://anxia.com/s/swhyiia3wzi?password=h374'
#  -H 'Sec-Fetch-Dest: empty'
#  -H 'Sec-Fetch-Mode: cors'
#  -H 'Sec-Fetch-Site: same-origin'
#  -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36'
#  -H 'X-Requested-With: XMLHttpRequest'
#  -H 'sec-ch-ua: "Google Chrome";v="131", "Chromium";v="131", "Not_A Brand";v="24"'
#  -H 'sec-ch-ua-mobile: ?0'
#  -H 'sec-ch-ua-platform: "Windows"'
#  --data-raw 'share_code=swhyiia3wzi&receive_code=h374&file_id=2532636713782843636'
POST https://anxia.com/webapi/share/skip_login_downurl
Accept: application/json, text/javascript, */*; q=0.01
Accept-Language: zh-CN,zh;q=0.9,en;q=0.8
Cache-Control: no-cache
Connection: keep-alive
Cookie: acw_tc=2f6a1fdb17343237335965711ee089dd42f90058dbad48c86a96931b7098b0
DNT: 1
Origin: https://anxia.com
Pragma: no-cache
Referer: https://anxia.com/s/swhyiia3wzi?password=h374
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
X-Requested-With: XMLHttpRequest
sec-ch-ua: "Google Chrome";v="131", "Chromium";v="131", "Not_A Brand";v="24"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Windows"
Content-Type: application/x-www-form-urlencoded; charset=UTF-8

share_code=swhyiia3wzi&receive_code=h374&file_id=2532636713782843636

###
# @no-cookie-jar
# curl 'https://anxia.com/webapi/share/snap?share_code=swhyiia3wzi&offset=0&limit=20&receive_code=h374&cid='
#  -H 'Accept: application/json, text/javascript, */*; q=0.01'
#  -H 'Accept-Language: zh-CN,zh;q=0.9,en;q=0.8'
#  -H 'Cache-Control: no-cache'
#  -H 'Connection: keep-alive'
#  -H 'Cookie: acw_tc=2f6a1fdb17343237335965711ee089dd42f90058dbad48c86a96931b7098b0'
#  -H 'DNT: 1'
#  -H 'Pragma: no-cache'
#  -H 'Referer: https://anxia.com/s/swhyiia3wzi?password=h374'
#  -H 'Sec-Fetch-Dest: empty'
#  -H 'Sec-Fetch-Mode: cors'
#  -H 'Sec-Fetch-Site: same-origin'
#  -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36'
#  -H 'X-Requested-With: XMLHttpRequest'
#  -H 'sec-ch-ua: "Google Chrome";v="131", "Chromium";v="131", "Not_A Brand";v="24"'
#  -H 'sec-ch-ua-mobile: ?0'
#  -H 'sec-ch-ua-platform: "Windows"'
GET https://anxia.com/webapi/share/snap?share_code=swhyiia3wzi&offset=0&limit=20&receive_code=h374&cid=
Accept: application/json, text/javascript, */*; q=0.01
Accept-Language: zh-CN,zh;q=0.9,en;q=0.8
Cache-Control: no-cache
Connection: keep-alive
DNT: 1
Pragma: no-cache
Referer: https://anxia.com/s/swhyiia3wzi?password=h374
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
X-Requested-With: XMLHttpRequest
sec-ch-ua: "Google Chrome";v="131", "Chromium";v="131", "Not_A Brand";v="24"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Windows"

###


