# curl 'https://ip.ihuan.me/tqdl.html'
#  -H 'accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7'
#  -H 'accept-language: zh-CN,zh;q=0.9,en;q=0.8'
#  -H 'cache-control: no-cache'
#  -H 'content-type: application/x-www-form-urlencoded'
#  -H 'cookie: 91e73cee101cc3ecefd9ca31a227d508=4380c9f80effb56e85210a54dc286c06; statistics=16453d6e2683b8800ded2a27c7f595d9; Hm_lvt_8ccd0ef22095c2eebfe4cd6187dea829=1727664099; HMACCOUNT=AA7CAD3BA9E39EC8; 28114211b4e11617bd725475433e69aa=29d9778b3f2c1b30c137fef0d6728e29; Hm_lpvt_8ccd0ef22095c2eebfe4cd6187dea829=1727667138'
#  -H 'dnt: 1'
#  -H 'origin: https://ip.ihuan.me'
#  -H 'pragma: no-cache'
#  -H 'priority: u=0, i'
#  -H 'referer: https://ip.ihuan.me/ti.html'
#  -H 'sec-ch-ua: "Google Chrome";v="129", "Not=A?Brand";v="8", "Chromium";v="129"'
#  -H 'sec-ch-ua-mobile: ?0'
#  -H 'sec-ch-ua-platform: "Windows"'
#  -H 'sec-fetch-dest: document'
#  -H 'sec-fetch-mode: navigate'
#  -H 'sec-fetch-site: same-origin'
#  -H 'sec-fetch-user: ?1'
#  -H 'upgrade-insecure-requests: 1'
#  -H 'user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36'
#  --data-raw 'num=100&port=&kill_port=&address=&kill_address=&anonymity=&type=&post=&sort=&key=15146aca2e04e3756a2e79ec33ca5679'
#@no-cookie-jar
POST https://ip.ihuan.me/tqdl.html
accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
accept-language: zh-CN,zh;q=0.9,en;q=0.8
cache-control: no-cache
cookie: 91e73cee101cc3ecefd9ca31a227d508=4380c9f80effb56e85210a54dc286c06; statistics=16453d6e2683b8800ded2a27c7f595d9; Hm_lvt_8ccd0ef22095c2eebfe4cd6187dea829=1727664099; HMACCOUNT=AA7CAD3BA9E39EC8; 28114211b4e11617bd725475433e69aa=29d9778b3f2c1b30c137fef0d6728e29; Hm_lpvt_8ccd0ef22095c2eebfe4cd6187dea829=1727667138
dnt: 1
origin: https://ip.ihuan.me
pragma: no-cache
priority: u=0, i
referer: https://ip.ihuan.me/ti.html
sec-ch-ua: "Google Chrome";v="129", "Not=A?Brand";v="8", "Chromium";v="129"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Windows"
sec-fetch-dest: document
sec-fetch-mode: navigate
sec-fetch-site: same-origin
sec-fetch-user: ?1
upgrade-insecure-requests: 1
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
Content-Type: application/x-www-form-urlencoded

num=100&port=&kill_port=&address=&kill_address=&anonymity=&type=&post=&sort=&key=15146aca2e04e3756a2e79ec33ca5679

###
https://ip.ihuan.me/
accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
accept-language: zh-CN,zh;q=0.9,en;q=0.8
cache-control: no-cache
#cookie: 91e73cee101cc3ecefd9ca31a227d508=4380c9f80effb56e85210a54dc286c06; statistics=16453d6e2683b8800ded2a27c7f595d9; Hm_lvt_8ccd0ef22095c2eebfe4cd6187dea829=1727664099; HMACCOUNT=AA7CAD3BA9E39EC8; 28114211b4e11617bd725475433e69aa=29d9778b3f2c1b30c137fef0d6728e29; Hm_lpvt_8ccd0ef22095c2eebfe4cd6187dea829=1727667138
dnt: 1
origin: https://ip.ihuan.me
pragma: no-cache
priority: u=0, i
referer: https://ip.ihuan.me
sec-ch-ua: "Google Chrome";v="129", "Not=A?Brand";v="8", "Chromium";v="129"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Windows"
sec-fetch-dest: document
sec-fetch-mode: navigate
sec-fetch-site: same-origin
sec-fetch-user: ?1
upgrade-insecure-requests: 1
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
Content-Type: application/x-www-form-urlencoded

###
GET https://blog.qaiu.top/api/v3/share/download/nLNsQ

###
# @no-redirect
GET http://127.0.0.1:6401/parser?url=https://blog.qaiu.top/s/nLNsQ1

###
# @no-redirect
GET http://127.0.0.1:6401/parser?url=https://pan.baidu.com/s/1o7ZPmAecYJ4rsxibyARyeg?pwd=QAIU

###
https://pan.baidu.com/s/1o7ZPmAecYJ4rsxibyARyeg?pwd=QAIU



### 微雨云存储 0. 带密码 获取分享ID: QMa6ie
https://www.vyuyun.com/s/QMa6ie?password=I4KG7H
### 微雨云存储 0. 不带密码 获取分享ID: jemOTl
https://www.vyuyun.com/s/jemOTl?password=

### 微雨云存储 1. 传入jemOTl 获取文件ID json: data->id
https://www.vyuyun.com/apiv1/share/file/jemOTl?password=
### 微雨云存储 1. 传入jemOTl 获取文件ID json: data->id
https://www.vyuyun.com/apiv1/share/file/QMa6ie?password=I4KG7H

### 微雨云存储 2. 获取文件直链 json: data->downInfo->url
https://www.vyuyun.com/apiv1/share/getShareDownUrl/jemOTl/0BEmf4?password=
referer: https://www.vyuyun.com


### 下载直链 无需请求头 11:00
#@no-cookie-jar
https://down2.bilnn.top/uploads/11283/306bdccd233ffd2c.jar?filename=C400003mAan70zUy5O+%282%29.m4a&mime=audio%2Fx-m4a&verify=1729911697-SLZtEHXB4TM*ze1j31WMyNA**p743DY*GN2sajUx5w*2mM**


###
# @no-cookie-jar
# curl 'https://www.vyuyun.com/apiv1/share/getShareDownUrl/QPyZsb/gDZBTm?password=&downcode=Iv7YsjhM_6kzHijjtHyTLfPqlr6xwR5kqVNfMMAdWBEBcW1iNNIK-hDvrwLyzF4a'
#  -H 'Accept: */*'
#  -H 'Accept-Language: zh-CN,zh;q=0.9,en;q=0.8'
#  -H 'Cache-Control: no-cache'
#  -H 'Connection: keep-alive'
#  -H 'Cookie: Hm_lvt_6e5421de7bb814e1dfc49bbc577c04d3=1734489414,1736133991,1736139184; HMACCOUNT=7C4EDB1414D4E56F; ginmin-session=MTczNjEzOTY5OHxEWDhFQVFMX2dBQUJFQUVRQUFBRV80QUFBQT09fE1kmd-TQNIU-AcLRbEhAMzpcoaTIqnDkU_z1Z2kW64A; Hm_lpvt_6e5421de7bb814e1dfc49bbc577c04d3=1736139719; __gads=ID=710230eb796d6baf:T=1736139187:RT=1736139729:S=ALNI_MauDIW3Tl0IYOZILi-6C0qMU328RA; __gpi=UID=00000fa7e525a50e:T=1736139187:RT=1736139729:S=ALNI_MYOvo89qg4zJq0s35CanMI3lx-zLw; __eoi=ID=df2245386092f112:T=1736139187:RT=1736139729:S=AA-AfjbzvOhiQPaERKQKlmEEC7Ds'
#  -H 'DNT: 1'
#  -H 'Pragma: no-cache'
#  -H 'Referer: https://www.vyuyun.com/s/QPyZsb/file?password='
#  -H 'Sec-Fetch-Dest: empty'
#  -H 'Sec-Fetch-Mode: cors'
#  -H 'Sec-Fetch-Site: same-origin'
#  -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36'
#  -H 'sec-ch-ua: "Google Chrome";v="131", "Chromium";v="131", "Not_A Brand";v="24"'
#  -H 'sec-ch-ua-mobile: ?0'
#  -H 'sec-ch-ua-platform: "Windows"'
#  -H 'token;'
GET https://www.vyuyun.com/apiv1/share/getShareDownUrl/QPyZsb/gDZBTm?password=&downcode=Iv7YsjhM_6kzHijjtHyTLfPqlr6xwR5kqVNfMMAdWBEBcW1iNNIK-hDvrwLyzF4a
Accept: */*
Accept-Language: zh-CN,zh;q=0.9,en;q=0.8
Cache-Control: no-cache
Connection: keep-alive
Cookie: Hm_lvt_6e5421de7bb814e1dfc49bbc577c04d3=1734489414,1736133991,1736139184; HMACCOUNT=7C4EDB1414D4E56F; ginmin-session=MTczNjEzOTY5OHxEWDhFQVFMX2dBQUJFQUVRQUFBRV80QUFBQT09fE1kmd-TQNIU-AcLRbEhAMzpcoaTIqnDkU_z1Z2kW64A; Hm_lpvt_6e5421de7bb814e1dfc49bbc577c04d3=1736139719; __gads=ID=710230eb796d6baf:T=1736139187:RT=1736139729:S=ALNI_MauDIW3Tl0IYOZILi-6C0qMU328RA; __gpi=UID=00000fa7e525a50e:T=1736139187:RT=1736139729:S=ALNI_MYOvo89qg4zJq0s35CanMI3lx-zLw; __eoi=ID=df2245386092f112:T=1736139187:RT=1736139729:S=AA-AfjbzvOhiQPaERKQKlmEEC7Ds
DNT: 1
Pragma: no-cache
Referer: https://www.vyuyun.com/s/QPyZsb/file?password=
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
sec-ch-ua: "Google Chrome";v="131", "Chromium";v="131", "Not_A Brand";v="24"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Windows"
token:

###



###
# curl 'https://www.vyuyun.com/apiv1/share/file/QPyZsb?password='
#  -H 'Accept: application/json, text/plain, */*'
#  -H 'Accept-Language: zh-CN,zh;q=0.9,en;q=0.8'
#  -H 'Cache-Control: no-cache'
#  -H 'Connection: keep-alive'
#  -H 'Cookie: Hm_lvt_6e5421de7bb814e1dfc49bbc577c04d3=1734489414,1736133991; HMACCOUNT=845216228CFDAEF3; ginmin-session=MTczNjEzNzIwNXxEWDhFQVFMX2dBQUJFQUVRQUFBaV80QUFBUVp6ZEhKcGJtY01CUUFEWVdsa0JuTjBjbWx1Wnd3SEFBVXhNVGt3T0E9PXygMqAo7e0FsZpAm5tggrVEAmipmptNAe4RF-StdbItOA==; __gads=ID=02846a0224427b16:T=1729911643:RT=1736137206:S=ALNI_MYN-82qd45RW0rYq1JewWVxCmoZAQ; __gpi=UID=00000f553e085dd5:T=1729911643:RT=1736137206:S=ALNI_Mb2dIMzZrO14lDlqCBOShH29OEfng; __eoi=ID=3e810b8ce65b0a46:T=1729911643:RT=1736137206:S=AA-AfjbN5kpzrPK6QBBlTEmMlxXx; Hm_lpvt_6e5421de7bb814e1dfc49bbc577c04d3=1736137222'
#  -H 'DNT: 1'
#  -H 'Pragma: no-cache'
#  -H 'Referer: https://www.vyuyun.com/s/QPyZsb/file?password='
#  -H 'Sec-Fetch-Dest: empty'
#  -H 'Sec-Fetch-Mode: cors'
#  -H 'Sec-Fetch-Site: same-origin'
#  -H 'Token;'
#  -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36'
#  -H 'X-Requested-With: XMLHttpRequest'
#  -H 'sec-ch-ua: "Google Chrome";v="131", "Chromium";v="131", "Not_A Brand";v="24"'
#  -H 'sec-ch-ua-mobile: ?0'
#  -H 'sec-ch-ua-platform: "Windows"'
GET https://www.vyuyun.com/apiv1/share/file/QPyZsb?password=
Accept: application/json, text/plain, */*
Accept-Language: zh-CN,zh;q=0.9,en;q=0.8
Cache-Control: no-cache
Connection: keep-alive
Cookie: Hm_lvt_6e5421de7bb814e1dfc49bbc577c04d3=1734489414,1736133991; HMACCOUNT=845216228CFDAEF3; ginmin-session=MTczNjEzNzIwNXxEWDhFQVFMX2dBQUJFQUVRQUFBaV80QUFBUVp6ZEhKcGJtY01CUUFEWVdsa0JuTjBjbWx1Wnd3SEFBVXhNVGt3T0E9PXygMqAo7e0FsZpAm5tggrVEAmipmptNAe4RF-StdbItOA==; __gads=ID=02846a0224427b16:T=1729911643:RT=1736137206:S=ALNI_MYN-82qd45RW0rYq1JewWVxCmoZAQ; __gpi=UID=00000f553e085dd5:T=1729911643:RT=1736137206:S=ALNI_Mb2dIMzZrO14lDlqCBOShH29OEfng; __eoi=ID=3e810b8ce65b0a46:T=1729911643:RT=1736137206:S=AA-AfjbN5kpzrPK6QBBlTEmMlxXx; Hm_lpvt_6e5421de7bb814e1dfc49bbc577c04d3=1736137222
DNT: 1
Pragma: no-cache
Referer: https://www.vyuyun.com/s/QPyZsb/file?password=
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
Token:
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
X-Requested-With: XMLHttpRequest
sec-ch-ua: "Google Chrome";v="131", "Chromium";v="131", "Not_A Brand";v="24"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Windows"

###
# curl 'https://www.vyuyun.com/apiv1/share/getShareDownUrl/QPyZsb/gDZBTm?password=&downcode=Iv7YsjhM_6kzHijjtHyTLT2CySejYHyXEtW_2oI9kqCnevPaRjMpzFDaq4dT4z3R'
#  -H 'Accept: */*'
#  -H 'Accept-Language: zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6'
#  -H 'Cache-Control: no-cache'
#  -H 'Connection: keep-alive'
#  -H 'Cookie: noticeId=1; Hm_lvt_6e5421de7bb814e1dfc49bbc577c04d3=1736134006; HMACCOUNT=DD7A065B1B5C7BCF; ginmin-session=MTczNjEzNDExNXxEWDhFQVFMX2dBQUJFQUVRQUFELUFRal9nQUFEQm5OMGNtbHVad3dIQUFWMGIydGxiZ1p6ZEhKcGJtY01fNjhBXzZ4b1pVOVNMWGRwVVRWemVrTlFhRGxzTjNCRlNHOW5jMWRLU2pKVFluUlZOVWR2UlhkWGNEbElUMEZNYlV0RVMwRkJTeloxVlhaS1UycE5aMXBrTW1jMWJYVlRPVjlOWkVVMWNHMU1iMkZMTW1sR1NHcFhRbWhPWjAxb05FWmpWV2swVWpOU01GZE9aRk5UZUd0WVJFSmphMWw0WVZKVkxYRlhSalZ5UlhSSmRYaG9jbVJuTWpkbmRFWlBWRlpDV0ZkWGMzWjJaVFZtUjFwSWMwRnBlbXhhUVROVFowaEtZakJqTlc4cUJuTjBjbWx1Wnd3SUFBWnZjR1Z1YVdRR2MzUnlhVzVuREFJQUFBWnpkSEpwYm1jTUNnQUlZV1J0YVc1ZmFYTUdjM1J5YVc1bkRBTUFBVEE9fMMethsDCW-b_YQHRj_0KHUVB1AcmohDXI4L4en8_8Nd; Hm_lpvt_6e5421de7bb814e1dfc49bbc577c04d3=1736138831'
#  -H 'DNT: 1'
#  -H 'Pragma: no-cache'
#  -H 'Referer: https://www.vyuyun.com/s/QPyZsb/file?password='
#  -H 'Sec-Fetch-Dest: empty'
#  -H 'Sec-Fetch-Mode: cors'
#  -H 'Sec-Fetch-Site: same-origin'
#  -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36 Edg/131.0.0.0'
#  -H 'sec-ch-ua: "Microsoft Edge";v="131", "Chromium";v="131", "Not_A Brand";v="24"'
#  -H 'sec-ch-ua-mobile: ?0'
#  -H 'sec-ch-ua-platform: "Windows"'
#  -H 'token: heOR-wiQ5szCPh9l7pEHogsWJJ2SbtU5GoEwWp9HOALmKDKAAK6uUvJSjMgZd2g5muS9_MdE5pmLoaK2iFHjWBhNgMh4FcUi4R3R0WNdSSxkXDBckYxaRU-qWF5rEtIuxhrdg27gtFOTVBXWWsvve5fGZHsAizlZA3SgHJb0c5o*'
GET https://www.vyuyun.com/apiv1/share/getShareDownUrl/QPyZsb/gDZBTm?password=&downcode=Iv7YsjhM_6kzHijjtHyTLT2CySejYHyXEtW_2oI9kqCnevPaRjMpzFDaq4dT4z3R
Accept: */*
Accept-Language: zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6
Cache-Control: no-cache
Connection: keep-alive
Cookie: noticeId=1; Hm_lvt_6e5421de7bb814e1dfc49bbc577c04d3=1736134006; HMACCOUNT=DD7A065B1B5C7BCF; ginmin-session=MTczNjEzNDExNXxEWDhFQVFMX2dBQUJFQUVRQUFELUFRal9nQUFEQm5OMGNtbHVad3dIQUFWMGIydGxiZ1p6ZEhKcGJtY01fNjhBXzZ4b1pVOVNMWGRwVVRWemVrTlFhRGxzTjNCRlNHOW5jMWRLU2pKVFluUlZOVWR2UlhkWGNEbElUMEZNYlV0RVMwRkJTeloxVlhaS1UycE5aMXBrTW1jMWJYVlRPVjlOWkVVMWNHMU1iMkZMTW1sR1NHcFhRbWhPWjAxb05FWmpWV2swVWpOU01GZE9aRk5UZUd0WVJFSmphMWw0WVZKVkxYRlhSalZ5UlhSSmRYaG9jbVJuTWpkbmRFWlBWRlpDV0ZkWGMzWjJaVFZtUjFwSWMwRnBlbXhhUVROVFowaEtZakJqTlc4cUJuTjBjbWx1Wnd3SUFBWnZjR1Z1YVdRR2MzUnlhVzVuREFJQUFBWnpkSEpwYm1jTUNnQUlZV1J0YVc1ZmFYTUdjM1J5YVc1bkRBTUFBVEE9fMMethsDCW-b_YQHRj_0KHUVB1AcmohDXI4L4en8_8Nd; Hm_lpvt_6e5421de7bb814e1dfc49bbc577c04d3=1736138831
DNT: 1
Pragma: no-cache
Referer: https://www.vyuyun.com/s/QPyZsb/file?password=
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36 Edg/131.0.0.0
sec-ch-ua: "Microsoft Edge";v="131", "Chromium";v="131", "Not_A Brand";v="24"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Windows"
token: heOR-wiQ5szCPh9l7pEHogsWJJ2SbtU5GoEwWp9HOALmKDKAAK6uUvJSjMgZd2g5muS9_MdE5pmLoaK2iFHjWBhNgMh4FcUi4R3R0WNdSSxkXDBckYxaRU-qWF5rEtIuxhrdg27gtFOTVBXWWsvve5fGZHsAizlZA3SgHJb0c5o*

###






### 118网盘 https://qaiu.118pan.com/b1228264
#密码：qaiu
https://qaiu.118pan.com/b1228264

###
https://xiguage.118pan.com/b1186280

###  118 b1228264->1228264
POST https://qaiu.118pan.com/ajax.php
Content-Type: application/x-www-form-urlencoded; charset=UTF-8

action=load_down_addr1&file_id=1228264

###  118 b1186280->1186280
POST https://qaiu.118pan.com/ajax.php
Content-Type: application/x-www-form-urlencoded; charset=UTF-8

action=load_down_addr1&file_id=1186280

###
#@no-redirect
https://nsub2d3.118pan.com/dl.php?M2E0NFVEMGM4YnFOenc2dHI5MGp1MEV3MUhvbW1sYXhnUkxLbHg3clhkMDhld24vZFBpazhlNTVTKytEY1IvRUhsWUZxT1lGYWNZUmtaNU9KMnNDQll3NzNYbFVUVU1Uc09CUUQrSHVyajR4RmpSczdsYS8zVUpmNzdkTlJHSG9FMnpNcEJuWnhnVCtiUVBoelE4S1c3WW8xczI2bEZsb3hTSlYvdis4dTk0My9TS2lKbzNLcXpLUmVNN1NPMlhHaWc4Tlo3TVlKQ3g3OHdOWW9mMzhMVk9tRThWdVBzZU1XZHFzTVR5cDE1aEFiU2o4ZkZ1SThwZXRNdGdPQmtOdEJvejRiS0pmMTFNS3Bn


### https://qscbm187531.118pan.com/b1102853
#@no-redirect
POST https://qscbm187531.118pan.com/ajax.php
Content-Type: application/x-www-form-urlencoded; charset=UTF-8

### ABFD0A26E47D3458
#@no-redirect
# -> https://onedrive.live.com/redir?resid=ABFD0A26E47D3458!4698&authkey=!ACpvXghP5xhG_cg&e=hV98W1
https://1drv.ms/u/s!Alg0feQmCv2rpFoqb14IT-cYRv3I?e=hV98W1


### "@content.downloadUrl"
https://api.onedrive.com/v1.0/drives/abfd0a26e47d3458/items/ABFD0A26E47D3458!4698?authkey=!ACpvXghP5xhG_cg



### https://onedrive.live.com/redir?resid=ABFD0A26E47D3458!3729&authkey=!AF3rQNA6Yxr46H8&ithint=file%2cdocx&e=buaRtp
### https://onedrive.live.com/redir?resid=ABFD0A26E47D3458!3729&ithint=file%2cdocx&e=buaRtp&migratedtospo=true&redeem=aHR0cHM6Ly8xZHJ2Lm1zL3cvcyFBbGcwZmVRbUN2MnJuUkZkNjBEUU9tTWEtT2hfP2U9YnVhUnRw
#@no-redirect
https://1drv.ms/w/s!Alg0feQmCv2rnRFd60DQOmMa-Oh_?e=buaRtp

###
https://api.onedrive.com/v1.0/drives/abfd0a26e47d3458/items/ABFD0A26E47D3458!3729?authkey=!AF3rQNA6Yxr46H8

###
#@no-redirect
https://1drv.ms/u/s!Alg0feQmCv2rpFvu444hg5yVqDcK?e=OggA4s

###
#@no-redirect
https://onedrive.live.com/redir?resid=ABFD0A26E47D3458!4699&authkey=!AO7jjiGDnJWoNwo&e=OggA4s

###
https://api.onedrive.com/v1.0/drives/abfd0a26e47d3458/items/ABFD0A26E47D3458!4699?authkey=!AO7jjiGDnJWoNwo

### 谷歌云盘
https://drive.google.com/file/d/1iofiAmFs2NaBHp4OyeIo7sbVX-jQ0imB/view?usp=sharing
###
https://drive.google.com/file/d/151bR-nk-tOBm9QAFaozJIVt2WYyCMkoz/view?usp=drive_link
#302链
#https://drive.usercontent.google.com/uc?id=1iofiAmFs2NaBHp4OyeIo7sbVX-jQ0imB&export=download
#直链
#https://drive.usercontent.google.com/download?id=1iofiAmFs2NaBHp4OyeIo7sbVX-jQ0imB&export=download

#https://drive.usercontent.google.com/download?id=151bR-nk-tOBm9QAFaozJIVt2WYyCMkoz&export=download&confirm=t&uuid=bb8870cb-debd-4ba0-b239-aca14b6a9782&at=AENtkXYr-p2Bv0EDgKyXyYcZwOwA%3A1730526150700
#https://drive.usercontent.google.com/download?id=151bR-nk-tOBm9QAFaozJIVt2WYyCMkoz&export=download&confirm=t&uuid=c9bb0ec9-3858-47a5-8cc1-979145b9d866&at=AENtkXaWSisZ7HO9EqxoIdY_38tX%3A1730526571780
#https://drive.usercontent.google.com/download?id=1_qu7GTFzIm9GpUtzSmn8F8SOn3fqaOOu&export=download&confirm=t&uuid=&at=AENtkXaWSisZ7HO9EqxoIdY_38tX%3A1730526571780

