# curl 'https://ip.ihuan.me/tqdl.html'
#  -H 'accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7'
#  -H 'accept-language: zh-CN,zh;q=0.9,en;q=0.8'
#  -H 'cache-control: no-cache'
#  -H 'content-type: application/x-www-form-urlencoded'
#  -H 'cookie: 91e73cee101cc3ecefd9ca31a227d508=4380c9f80effb56e85210a54dc286c06; statistics=16453d6e2683b8800ded2a27c7f595d9; Hm_lvt_8ccd0ef22095c2eebfe4cd6187dea829=1727664099; HMACCOUNT=AA7CAD3BA9E39EC8; 28114211b4e11617bd725475433e69aa=29d9778b3f2c1b30c137fef0d6728e29; Hm_lpvt_8ccd0ef22095c2eebfe4cd6187dea829=1727667138'
#  -H 'dnt: 1'
#  -H 'origin: https://ip.ihuan.me'
#  -H 'pragma: no-cache'
#  -H 'priority: u=0, i'
#  -H 'referer: https://ip.ihuan.me/ti.html'
#  -H 'sec-ch-ua: "Google Chrome";v="129", "Not=A?Brand";v="8", "Chromium";v="129"'
#  -H 'sec-ch-ua-mobile: ?0'
#  -H 'sec-ch-ua-platform: "Windows"'
#  -H 'sec-fetch-dest: document'
#  -H 'sec-fetch-mode: navigate'
#  -H 'sec-fetch-site: same-origin'
#  -H 'sec-fetch-user: ?1'
#  -H 'upgrade-insecure-requests: 1'
#  -H 'user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36'
#  --data-raw 'num=100&port=&kill_port=&address=&kill_address=&anonymity=&type=&post=&sort=&key=15146aca2e04e3756a2e79ec33ca5679'
#@no-cookie-jar
POST https://ip.ihuan.me/tqdl.html
accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
accept-language: zh-CN,zh;q=0.9,en;q=0.8
cache-control: no-cache
cookie: 91e73cee101cc3ecefd9ca31a227d508=4380c9f80effb56e85210a54dc286c06; statistics=16453d6e2683b8800ded2a27c7f595d9; Hm_lvt_8ccd0ef22095c2eebfe4cd6187dea829=1727664099; HMACCOUNT=AA7CAD3BA9E39EC8; 28114211b4e11617bd725475433e69aa=29d9778b3f2c1b30c137fef0d6728e29; Hm_lpvt_8ccd0ef22095c2eebfe4cd6187dea829=1727667138
dnt: 1
origin: https://ip.ihuan.me
pragma: no-cache
priority: u=0, i
referer: https://ip.ihuan.me/ti.html
sec-ch-ua: "Google Chrome";v="129", "Not=A?Brand";v="8", "Chromium";v="129"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Windows"
sec-fetch-dest: document
sec-fetch-mode: navigate
sec-fetch-site: same-origin
sec-fetch-user: ?1
upgrade-insecure-requests: 1
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
Content-Type: application/x-www-form-urlencoded

num=100&port=&kill_port=&address=&kill_address=&anonymity=&type=&post=&sort=&key=15146aca2e04e3756a2e79ec33ca5679

###
https://ip.ihuan.me/
accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
accept-language: zh-CN,zh;q=0.9,en;q=0.8
cache-control: no-cache
#cookie: 91e73cee101cc3ecefd9ca31a227d508=4380c9f80effb56e85210a54dc286c06; statistics=16453d6e2683b8800ded2a27c7f595d9; Hm_lvt_8ccd0ef22095c2eebfe4cd6187dea829=1727664099; HMACCOUNT=AA7CAD3BA9E39EC8; 28114211b4e11617bd725475433e69aa=29d9778b3f2c1b30c137fef0d6728e29; Hm_lpvt_8ccd0ef22095c2eebfe4cd6187dea829=1727667138
dnt: 1
origin: https://ip.ihuan.me
pragma: no-cache
priority: u=0, i
referer: https://ip.ihuan.me
sec-ch-ua: "Google Chrome";v="129", "Not=A?Brand";v="8", "Chromium";v="129"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Windows"
sec-fetch-dest: document
sec-fetch-mode: navigate
sec-fetch-site: same-origin
sec-fetch-user: ?1
upgrade-insecure-requests: 1
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
Content-Type: application/x-www-form-urlencoded

###
GET https://blog.qaiu.top/api/v3/share/download/nLNsQ

###
# @no-redirect
GET http://127.0.0.1:6401/parser?url=https://blog.qaiu.top/s/nLNsQ1

###
# @no-redirect
GET http://127.0.0.1:6401/parser?url=https://pan.baidu.com/s/1o7ZPmAecYJ4rsxibyARyeg?pwd=QAIU

###
https://pan.baidu.com/s/1o7ZPmAecYJ4rsxibyARyeg?pwd=QAIU



### 微雨云存储 0. 带密码 获取分享ID: QMa6ie
https://www.vyuyun.com/s/QMa6ie?password=I4KG7H
### 微雨云存储 0. 不带密码 获取分享ID: jemOTl
https://www.vyuyun.com/s/jemOTl?password=

### 微雨云存储 1. 传入jemOTl 获取文件ID json: data->id
https://www.vyuyun.com/apiv1/share/file/jemOTl?password=
### 微雨云存储 1. 传入jemOTl 获取文件ID json: data->id
https://www.vyuyun.com/apiv1/share/file/QMa6ie?password=I4KG7H

### 微雨云存储 2. 获取文件直链 json: data->downInfo->url
https://www.vyuyun.com/apiv1/share/getShareDownUrl/jemOTl/0BEmf4?password=
referer: https://www.vyuyun.com


### 下载直链 无需请求头 11:00
#@no-cookie-jar
https://down2.bilnn.top/uploads/11283/306bdccd233ffd2c.jar?filename=C400003mAan70zUy5O+%282%29.m4a&mime=audio%2Fx-m4a&verify=1729911697-SLZtEHXB4TM*ze1j31WMyNA**p743DY*GN2sajUx5w*2mM**


### 118网盘 https://qaiu.118pan.com/b1228264
#密码：qaiu
https://qaiu.118pan.com/b1228264

###
https://xiguage.118pan.com/b1186280

###  118 b1228264->1228264
POST https://qaiu.118pan.com/ajax.php
Content-Type: application/x-www-form-urlencoded; charset=UTF-8

action=load_down_addr1&file_id=1228264

###  118 b1186280->1186280
POST https://qaiu.118pan.com/ajax.php
Content-Type: application/x-www-form-urlencoded; charset=UTF-8

action=load_down_addr1&file_id=1186280

###
#@no-redirect
https://nsub2d3.118pan.com/dl.php?M2E0NFVEMGM4YnFOenc2dHI5MGp1MEV3MUhvbW1sYXhnUkxLbHg3clhkMDhld24vZFBpazhlNTVTKytEY1IvRUhsWUZxT1lGYWNZUmtaNU9KMnNDQll3NzNYbFVUVU1Uc09CUUQrSHVyajR4RmpSczdsYS8zVUpmNzdkTlJHSG9FMnpNcEJuWnhnVCtiUVBoelE4S1c3WW8xczI2bEZsb3hTSlYvdis4dTk0My9TS2lKbzNLcXpLUmVNN1NPMlhHaWc4Tlo3TVlKQ3g3OHdOWW9mMzhMVk9tRThWdVBzZU1XZHFzTVR5cDE1aEFiU2o4ZkZ1SThwZXRNdGdPQmtOdEJvejRiS0pmMTFNS3Bn


### https://qscbm187531.118pan.com/b1102853
#@no-redirect
POST https://qscbm187531.118pan.com/ajax.php
Content-Type: application/x-www-form-urlencoded; charset=UTF-8

### ABFD0A26E47D3458
#@no-redirect
# -> https://onedrive.live.com/redir?resid=ABFD0A26E47D3458!4698&authkey=!ACpvXghP5xhG_cg&e=hV98W1
https://1drv.ms/u/s!Alg0feQmCv2rpFoqb14IT-cYRv3I?e=hV98W1


### "@content.downloadUrl"
https://api.onedrive.com/v1.0/drives/abfd0a26e47d3458/items/ABFD0A26E47D3458!4698?authkey=!ACpvXghP5xhG_cg



### https://onedrive.live.com/redir?resid=ABFD0A26E47D3458!3729&authkey=!AF3rQNA6Yxr46H8&ithint=file%2cdocx&e=buaRtp
#@no-redirect
https://1drv.ms/w/s!Alg0feQmCv2rnRFd60DQOmMa-Oh_?e=buaRtp

###
https://api.onedrive.com/v1.0/drives/abfd0a26e47d3458/items/ABFD0A26E47D3458!3729?authkey=!AF3rQNA6Yxr46H8

###
#@no-redirect
https://1drv.ms/u/s!Alg0feQmCv2rpFvu444hg5yVqDcK?e=OggA4s

###
https://onedrive.live.com/redir?resid=ABFD0A26E47D3458!4699&authkey=!AO7jjiGDnJWoNwo&e=OggA4s

###
https://api.onedrive.com/v1.0/drives/abfd0a26e47d3458/items/ABFD0A26E47D3458!4699?authkey=!AO7jjiGDnJWoNwo
