###
POST https://lzzz.qaiu.top/v2/shout/submit
Content-Type: application/json

{
  "content": "ok 123123123123123123123123123123123123123123123123123123123123231123123"
}

###
GET http://lzzz.qaiu.top/v2/shout/retrieve?code=414016

###
响应:
{
"data": "这是一条秘密消息",
"code": 200,
"msg": "success"
}

###
https://gfs302n511.userstorage.mega.co.nz/dl/XwiiRG-Z97rz7wcbWdDmcd654FGkYU3FJncTobxhpPR9GVSggHJQsyMGdkLsWEiIIf71RUXcQPtV7ljVc0Z3tA_ThaUb9msdh7tS0z-2CbaRYSM5176DFxDKQtG84g