### 蓝奏云
# @no-redirect
GET http://127.0.0.1:6400/parser?url=https://lanzoux.com/ia2cntg

### 蓝奏云
# @no-redirect
GET http://127.0.0.1:6400/json/parser?url=https://wwsd.lanzoue.com/iLany1e9bbbi

### 蓝奏云
# @no-redirect
GET http://127.0.0.1:6400/lz/i6SqHmp1yfc
### 蓝奏云https://acgtools.lanzoui.com/iUr7Qnu3sxc  https://wwn.lanzouy.com/tp/ihLkw1gezutg https://wwn.lanzouy.com/ihLkw1gezutg
# @no-redirect
GET http://127.0.0.1:6400/lz/ihLkw1gezutg

### 蓝奏云
# @no-redirect
GET http://127.0.0.1:6400/lz/icBp6qqj82b@QAIU

### 蓝奏云
GET http://127.0.0.1:6400/json/lz/ia2cntg

### 蓝奏云优享
GET http://127.0.0.1:6400/json/iz/lGFndCM

###
GET http://127.0.0.1:6400/json/parser?url=https://www.ilanzou.com/s/lGFndCM
###
GET http://127.0.0.1:6400/json/parser?url=https://www.ilanzou.com/s/6XwnC4X
###
GET http://127.0.0.1:6400/json/parser?url=https://www.ilanzou.com/s/zHkna1S

### 奶牛
GET http://127.0.0.1:6400/json/cow/9a644fe3e3a748
Referer: https://cowtransfer.com/

### 奶牛
# @no-redirect
GET http://127.0.0.1:6400/cow/e4f41b51b5da4f
Referer: https://cowtransfer.com/

### 奶牛
# @no-redirect
GET http://127.0.0.1:6400/parser?url=https://cowtransfer.com/s/9a644fe3e3a748

### 奶牛
# @no-redirect
GET http://127.0.0.1:6400/parser?url=https://goldrepo.cowtransfer.com/s/026a638795634b

### 移动云空间 https://www.ecpan.cn/web/#/yunpanProxy?path=%2F%23%2Fdrive%2Foutside&data=81027a5c99af5b11ca004966c945cce6W9Bf2&isShare=1
# @no-redirect
GET http://127.0.0.1:6400/parser?url=https://www.ecpan.cn/web//yunpanProxy?path=%2F%23%2Fdrive%2Foutside&data=81027a5c99af5b11ca004966c945cce6W9Bf2&isShare=1

### 移动云空间 https://www.ecpan.cn/drive/fileextoverrid.do?chainUrlTemplate=https://www.ecpan.cn/web/#/yunpanProxy?path=%2F%23%2Fdrive%2Foutside&data=aa0cae0164d8885e6d35826b5b2901eckbWJBalM&parentId=-1
# @no-redirect
GET http://127.0.0.1:6400/ec/81027a5c99af5b11ca004966c945cce6W9Bf2

###
GET http://127.0.0.1:6400/json/ec/aa0cae0164d8885e6d35826b5b2901eckbWJBalM


### UC网盘
# @no-redirect
GET http://127.0.0.1:6400/uc/33197dd53ace4

### UC网盘
GET http://127.0.0.1:6400/json/uc/33197dd53ace4

### UC网盘
# @no-redirect
GET http://127.0.0.1:6400/parser?url=https://fast.uc.cn/s/33197dd53ace4


### 小飞机盘https://share.feijipan.com/s/nMtCOXL
# @no-redirect
GET http://127.0.0.1:6400/parser?url=https://share.feijipan.com/s/nMtCOXL

### 小飞机盘 https://share.feijipan.com/s/laUshYGk
# @no-redirect
GET http://127.0.0.1:6400/parser?url=https://share.feijipan.com/s/laUshYGk
### 小飞机盘
GET http://127.0.0.1:6400/json/fj/tIfhRqH
### 小飞机盘 https://share.feijipan.com/s/7jy0zlv
GET http://127.0.0.1:6400/json/fj/7jy0zlv

### 小飞机盘
# @no-redirect
GET http://127.0.0.1:6400/fj/tIfhRqH

### 360亿方云
# @no-redirect
GET http://127.0.0.1:6400/parser?url=https://v2.fangcloud.com/sharing/fb54bdf03c66c04334fe3687a3

### 360亿方云
GET http://127.0.0.1:6400/json/fc/fb54bdf03c66c04334fe3687a3

### 360亿方云
# @no-redirect
GET http://127.0.0.1:6400/fc/e5079007dc31226096628870c7@QAIU

#https://v2.fangcloud.com/sharing/e5079007dc31226096628870c7


# https://www.123pan.com/s/iaKtVv-ICECd.html
### 123
GET http://127.0.0.1:6400/json/ye/iaKtVv-ICECd
### 123
GET http://127.0.0.1:6400/json/ye/iaKtVv-6OECd@DcGe
### 123
GET https://lz.qaiu.top/json/ye/iaKtVv-6OECd@DcGe

### 123
# @no-redirect
GET http://127.0.0.1:6400/ye/iaKtVv-qOECd

### 123
# @no-redirect
GET http://127.0.0.1:6400/ye/Ev1lVv-t3SY3

### 123
# @no-redirect
GET http://127.0.0.1:6400/parser?url=https://www.123pan.com/s/iaKtVv-6OECd.html&pwd=DcGe


### 123
# @no-redirect
GET http://127.0.0.1:6400/parser?url=https://www.123pan.com/s/zF07Vv-WkHWd.html&pwd=bios


### 联想乐云
# @no-redirect
GET http://127.0.0.1:6400/parser?url=https://lecloud.lenovo.com/share/4DANWdRQsHHyiFB4a

### 联想乐云
# @no-redirect
GET http://127.0.0.1:6400/le/4DANWdRQsHHyiFB4a

### 联想乐云
# @no-redirect
GET http://127.0.0.1:6400/le/2RkKbLP9BrppS9b43@ex2b

### 联想乐云
GET http://127.0.0.1:6400/json/le/2RkKbLP9BrppS9b43@ex2b

### Cloudreve
GET http://127.0.0.1:6400/json/ce/https_pan.huang1111.cn_s_wDz5TK

### Cloudreve
GET http://127.0.0.1:6400/json/parser?url=https://pan.huang1111.cn/s/g31PcQ&pwd=qaiu

###
GET http://127.0.0.1:6400/v2/statisticsInfo

###
POST http://127.0.0.1:6400/v2/login?username=asd




