###
POST https://lzzz.qaiu.top/v2/shout/submit
Content-Type: application/json

{
  "content": "ok 123123123123123123123123123123123123123123123123123123123123231123123"
}

###
GET http://lzzz.qaiu.top/v2/shout/retrieve?code=414016

###
响应:
{
"data": "这是一条秘密消息",
"code": 200,
"msg": "success"
}

###
https://gfs302n511.userstorage.mega.co.nz/dl/XwiiRG-Z97rz7wcbWdDmcd654FGkYU3FJncTobxhpPR9GVSggHJQsyMGdkLsWEiIIf71RUXcQPtV7ljVc0Z3tA_ThaUb9msdh7tS0z-2CbaRYSM5176DFxDKQtG84g


###
POST http://127.0.0.1:6400/v2/playground/test
Content-Type: application/json

{
  "jsCode": "// ==UserScript==\n// @name DoS Test\n// @type dos_test\n// @displayName DoS\n// @match https://example\\.com/(?<KEY>\\w+)\n// @author hacker\n// @version 1.0.0\n// ==/UserScript==\n\nfunction parse(shareLinkInfo, http, logger) {\n    logger.info('Starting infinite loop...');\n    while(true) {\n        // Infinite loop - will hang the worker thread\n        var x = 1 + 1;\n    }\n    return 'never reached';\n}",
  "shareUrl": "https://example.com/test",
  "pwd": "",
  "method": "parse"
}